const ITEMS = [
  { name: "MOAW/Waffle Launcher", type: "Weapon", rarity: 100, power: 100, image: "images/MOAW.jpg" },
  { name: "Nuke Launcher", type: "Weapon", rarity: 59, power: 75, image: "images/nuke_launcher.png" },
  { name: "Radioactive Rudy", type: "Weapon", rarity: 90, power: 77, image: "images/radioactive_rudy.jpg" },
  { name: "Jack O Launcher", type: "Weapon", rarity: 90, power: 75, image: "images/jacko.jpg" },
  { name: "Bombardiro Launcher", type: "Weapon", rarity: 85, power: 60, image: "images/croc.png" },
  { name: "Goggles", type: "Tool", rarity: 80, power: 50, image: "images/goggles.jpg" },
  { name: "Classic Box", type: "Tool", rarity: 25, power: 15, image: "images/classic_box.jpg" },
  { name: "2025 Shrekmas Gift #10", type: "Tool", rarity: 6, power: 10, image: "images/2025_10.jpg" },
  { name: "Banana Gun", type: "Weapon", rarity: 3, power: 9, image: "images/banana_gun.jpg" },
  { name: "Wack Stick", type: "Weapon", rarity: 2, power: 12, image: "images/wack_stick.jpg" },
  { name: "Force Field Potion", type: "Tool", rarity: 1, power: 20, image: "images/force_field.jpg" },
  { name: "Med Kit", type: "Tool", rarity: 1, power: 12, image: "images/medkit.jpg" },
  { name: "2025 Shrekmas Gift #1", type: "Tool", rarity: 8, power: 10, image: "images/2025_1.jpg" },
  { name: "Baton", type: "Weapon", rarity: 4, power: 12, image: "images/baton.jpg" },
  { name: "Pistol", type: "Weapon", rarity: 8, power: 15, image: "images/pistol.jpg" },
  { name: "Antidonkey Spray", type: "Weapon", rarity: 5, power: 25, image: "images/antidonkey.jpg" },
  { name: "FlameThrower", type: "Weapon", rarity: 10, power: 30, image: "images/flamethrower.jpg" },
  { name: "AssaultRifle", type: "Weapon", rarity: 9, power: 18, image: "images/assault_rifle.jpg" },
  { name: "Radar", type: "Tool", rarity: 8, power: 25, image: "images/radar.jpg" },
  { name: "Jolly Grenade", type: "Weapon", rarity: 13, power: 18, image: "images/jolly_grenade.jpg" },
  { name: "Pumpkin Gun", type: "Weapon", rarity: 19, power: 22, image: "images/pumpkin_gun.jpg" },
  { name: "Quad Shotty", type: "Weapon", rarity: 10, power: 22, image: "images/quad_shotty.jpg" },
  { name: "Onion", type: "Tool", rarity: 3, power: 12, image: "images/onion.jpg" },
  { name: "Minigun", type: "Weapon", rarity: 16, power: 36, image: "images/minigun.jpg" },
  { name: "Freeze Ray", type: "Weapon", rarity: 6, power: 26, image: "images/freeze_ray.jpg" },
  { name: "Waffle Drink", type: "Tool", rarity: 16, power: 18, image: "images/waffle_drink.jpg" },
  { name: "Santa Socker", type: "Weapon", rarity: 11, power: 12, image: "images/santa_socker.jpg" },
  { name: "Crossbone", type: "Weapon", rarity: 13, power: 22, image: "images/crossbone.jpg" },
  { name: "Molotov", type: "Weapon", rarity: 2, power: 25, image: "images/molotov.jpg" },
  { name: "Dark Matter Rifle", type: "Weapon", rarity: 8, power: 35, image: "images/darkmatter.jpg" },
  { name: "Speed Potion", type: "Tool", rarity: 1, power: 18, image: "images/speed.jpg" },
  { name: "Camera", type: "Tool", rarity: 4, power: 4, image: "images/camera.jpg" },
  { name: "Boomstick", type: "Weapon", rarity: 14, power: 22, image: "images/boomstick.jpg" },
  { name: "Teddy Bomb", type: "Weapon", rarity: 12, power: 18, image: "images/teddy_bomb.jpg" },
  { name: "Gift Hammer", type: "Weapon", rarity: 15, power: 12, image: "images/gift_hammer.jpg" },
  { name: "Frosty Cola", type: "Tool", rarity: 10, power: 18, image: "images/frosty_cola.jpg" },
  { name: "Monkey Bomb", type: "Weapon", rarity: 12, power: 18, image: "images/monkey_bomb.jpg" },
  { name: "Ogre Bonker", type: "Weapon", rarity: 8, power: 12, image: "images/ogre_bonker.jpg" },
  { name: "BFG", type: "Weapon", rarity: 18, power: 32, image: "images/BFG.jpg" },
  { name: "Slurp Drink", type: "Tool", rarity: 12, power: 12, image: "images/slurp_drink.jpg" },
  { name: "Pickle Jar", type: "Tool", rarity: 13, power: 12, image: "images/pickle_jar.jpg" },
  { name: "Toxic Potion", type: "Tool", rarity: 13, power: 12, image: "images/toxic_potion.jpg" },
  { name: "Coin Finder", type: "Tool", rarity: 7, power: 15, image: "images/coin_finder.jpg" },
  { name: "Double Barrel", type: "Weapon", rarity: 11, power: 11, image: "images/double_barrel.jpg" },
  { name: "Gun", type: "Weapon", rarity: 15, power: 15, image: "images/gun.jpg" },
  { name: "2025 Shrekmas Gift #4", type: "Tool", rarity: 11, power: 10, image: "images/2025_4.jpg" },
  { name: "Bang Gun", type: "Tool", rarity: 8, power: 3, image: "images/bang_gun.jpg" },
  { name: "2025 Shrekmas Gift #3", type: "Tool", rarity: 12, power: 10, image: "images/2025_3.jpg" },
  { name: "Toy Plane", type: "Weapon", rarity: 12, power: 18, image: "images/toy_plane.jpg" },
  { name: "Spike Bat", type: "Weapon", rarity: 2, power: 12, image: "images/spike_bat.jpg" },
  { name: "Bloxy Cola", type: "Tool", rarity: 4, power: 18, image: "images/bloxy_cola.jpg" },
  { name: "Apple", type: "Tool", rarity: 13, power: 12, image: "images/apple.jpg" },
  { name: "Waffle Grenade", type: "Weapon", rarity: 16, power: 18, image: "images/waffle_grenade.jpg" },
  { name: "Firework Launcher", type: "Weapon", rarity: 20, power: 41, image: "images/firework_launcher.jpg" },
  { name: "Waffle Pan", type: "Weapon", rarity: 16, power: 12, image: "images/waffle_pan.jpg" },
  { name: "Christmas Tree Sword", type: "Weapon", rarity: 7, power: 12, image: "images/christmas_tree_sword.jpg" },
  { name: "Revolover", type: "Weapon", rarity: 16, power: 17, image: "images/revolover.jpg" },
  { name: "Recurve Bow", type: "Weapon", rarity: 16, power: 18, image: "images/recurve_bow.jpg" },
  { name: "Machete", type: "Weapon", rarity: 16, power: 12, image: "images/machete.jpg" },
  { name: "Chicken Wacker", type: "Weapon", rarity: 16, power: 12, image: "images/chicken_wacker.jpg" },
  { name: "Throwing Star", type: "Weapon", rarity: 16, power: 14, image: "images/throwing_star.jpg" },
  { name: "Sling Shot", type: "Weapon", rarity: 16, power: 15, image: "images/sling_shot.jpg" },
  { name: "Tung Bat", type: "Weapon", rarity: 11, power: 12, image: "images/tung_bat.jpg" },
  { name: "Turret", type: "Weapon", rarity: 5, power: 27, image: "images/turret.jpg" },
  { name: "Present Bomb", type: "Weapon", rarity: 8, power: 18, image: "images/present_bomb.jpg" },
  { name: "Spatula", type: "Weapon", rarity: 10, power: 12, image: "images/spatula.jpg" },
  { name: "Bear Trap", type: "Weapon", rarity: 4, power: 20, image: "images/bear_trap.jpg" },
  { name: "Metal Pipe", type: "Weapon", rarity: 10, power: 12, image: "images/metal_pipe.jpg" },
  { name: "2025 Shrekmas Gift #5", type: "Tool", rarity: 13, power: 10, image: "images/2025_5.jpg" },
  { name: "Office Chair", type: "Weapon", rarity: 13, power: 18, image: "images/office_chair.jpg" },
  { name: "Christmas Shotgun", type: "Weapon", rarity: 19, power: 18, image: "images/christmas_shotgun.jpg" },
  { name: "Baseball Bat", type: "Weapon", rarity: 13, power: 12, image: "images/baseball_bat.jpg" },
  { name: "Merry Pistol", type: "Weapon", rarity: 7, power: 15, image: "images/merry_pistol.jpg" },
  { name: "TikeCoupe", type: "Tool", rarity: 11, power: 23, image: "images/tyke.jpg" },
  { name: "Cappuccino", type: "Tool", rarity: 12, power: 18, image: "images/cappuccino.jpg" },
  { name: "Frosty Fury", type: "Weapon", rarity: 7, power: 12, image: "images/frosty_fury.jpg" },
  { name: "Candy Wacker", type: "Weapon", rarity: 7, power: 12, image: "images/candy_wacker.jpg" },
  { name: "Christmas Spirit", type: "Weapon", rarity: 7, power: 15, image: "images/christmas_spirit.jpg" },
  { name: "Ice Club", type: "Weapon", rarity: 7, power: 12, image: "images/ice_club.jpg" },
  { name: "Molotovio", type: "Weapon", rarity: 12, power: 25, image: "images/molotovio.jpg" },
  { name: "Jolly Jabber", type: "Weapon", rarity: 8, power: 12, image: "images/jolly_jabber.jpg" },
  { name: "Christmas Ak47", type: "Weapon", rarity: 10, power: 20, image: "images/christmas_ak47.jpg" },
  { name: "Proximity Balloon", type: "Weapon", rarity: 13, power: 18, image: "images/proximity_balloon.jpg" },
  { name: "Tongue Flicker", type: "Weapon", rarity: 16, power: 12, image: "images/tongue_flicker.jpg" },
  { name: "Toaster Gun", type: "Weapon", rarity: 23, power: 24, image: "images/toaster_gun.jpg" },
  { name: "Money Gun", type: "Weapon", rarity: 15, power: 39, image: "images/money_gun.jpg" },
  { name: "2025 Shrekmas Gift #2", type: "Tool", rarity: 15, power: 10, image: "images/2025_2.jpg" },
  { name: "2025 Shrekmas Gift #6", type: "Tool", rarity: 15, power: 10, image: "images/2025_6.jpg" },
  { name: "Pencil Bat", type: "Weapon", rarity: 18, power: 12, image: "images/pencil_bat.jpg" },
  { name: "Brrbrr Ak", type: "Weapon", rarity: 17, power: 20, image: "images/brrbrr.jpg" },
  { name: "Christmas AK", type: "Weapon", rarity: 16, power: 20, image: "images/christmas_ak.jpg" },
  { name: "Chainsaw", type: "Weapon", rarity: 18, power: 14, image: "images/chainsaw.jpg" },
  { name: "Pharaoh's Curse", type: "Weapon", rarity: 18, power: 28, image: "images/pharaoh.jpg" },
  { name: "Uzi", type: "Weapon", rarity: 20, power: 23, image: "images/uzi.jpg" },
  { name: "Shotgun", type: "Weapon", rarity: 20, power: 21, image: "images/shotgun.jpg" },
  { name: "AK47", type: "Weapon", rarity: 20, power: 20, image: "images/ak47.jpg" },
  { name: "2025 Shrekmas Gift #7", type: "Tool", rarity: 16, power: 10, image: "images/2025_7.jpg" },
  { name: "Tommy Gun", type: "Weapon", rarity: 20, power: 20, image: "images/tommy_gun.jpg" },
  { name: "MP5", type: "Weapon", rarity: 20, power: 18, image: "images/MP5.jpg" },
  { name: "Trench Shotgun", type: "Weapon", rarity: 20, power: 23, image: "images/trench_shotgun.jpg" },
  { name: "Clown Grenade", type: "Weapon", rarity: 20, power: 18, image: "images/clown_grenade.jpg" },
  { name: "Radio Bomb", type: "Weapon", rarity: 21, power: 18, image: "images/radio_bomb.jpg" },
  { name: "Grenade", type: "Weapon", rarity: 5, power: 18, image: "images/grenade.jpg" },
  { name: "Donkey Gun", type: "Weapon", rarity: 19, power: 20, image: "images/donkey_gun.jpg" },
  { name: "Proximity Mine", type: "Weapon", rarity: 7, power: 18, image: "images/proximity_mine.jpg" },
  { name: "Squid Hammer", type: "Weapon", rarity: 24, power: 12, image: "images/squid_hammer.jpg" },
  { name: "Bubble Gun", type: "Weapon", rarity: 22, power: 33, image: "images/bubble_gun.jpg" },
  { name: "Gingerbread Box", type: "Tool", rarity: 22, power: 20, image: "images/gingerbread_box.jpg" },
  { name: "Staple Gun", type: "Weapon", rarity: 22, power: 15, image: "images/stapler.jpg" },
  { name: "Enchanted Potion", type: "Tool", rarity: 25, power: 30, image: "images/enchanted_potion.jpg" },
  { name: "2025 Shrekmas Gift #9", type: "Tool", rarity: 18, power: 10, image: "images/2025_9.jpg" },
  { name: "Grenade Launcher", type: "Weapon", rarity: 25, power: 45, image: "images/grenade_launcher.jpg" },
  { name: "Keyboard", type: "Weapon", rarity: 20, power: 12, image: "images/keyboard.jpg" },
  { name: "Bat Pistol", type: "Weapon", rarity: 21, power: 15, image: "images/bat_pistol.jpg" },
  { name: "Ghost Trap", type: "Weapon", rarity: 23, power: 18, image: "images/ghost_trap.jpg" },
  { name: "Christmas Crossbow", type: "Weapon", rarity: 18, power: 16, image: "images/christmas_crossbow.jpg" },
  { name: "2025 Shrekmas Gift #8", type: "Tool", rarity: 19, power: 10, image: "images/2025_8.jpg" },
  { name: "Toxic Gun", type: "Weapon", rarity: 22, power: 22, image: "images/toxic_gun.jpg" },
  { name: "Missle Toe", type: "Weapon", rarity: 30, power: 50, image: "images/missletoe.jpg" },
  { name: "Shark Minigun", type: "Weapon", rarity: 27, power: 36, image: "images/shark_minigun.jpg" },
  { name: "Rad Rocker", type: "Weapon", rarity: 23, power: 12, image: "images/rad_rocker.jpg" },
  { name: "Clown Hammer", type: "Weapon", rarity: 22, power: 12, image: "images/clown_hammer.jpg" },
  { name: "Brainrot Box", type: "Tool", rarity: 30, power: 18, image: "images/brainrot_box.jpg" },
  { name: "Waffle Minigun", type: "Weapon", rarity: 34, power: 36, image: "images/waffle_minigun.jpg" },
  { name: "Ticket Minigun", type: "Weapon", rarity: 26, power: 36, image: "images/ticket_minigun.jpg" },
  { name: "Rudolph's Railgun", type: "Weapon", rarity: 30, power: 43, image: "images/rudolph_railgun.jpg" },
  { name: "Gingerbread Minigun", type: "Weapon", rarity: 30, power: 36, image: "images/gingerbread_minigun.jpg" },
  { name: "Pumpkin Bomb", type: "Weapon", rarity: 17, power: 18, image: "images/pumpkin_bomb.jpg" },
  { name: "North Pole", type: "Weapon", rarity: 21, power: 32, image: "images/north_pole.jpg" },
  { name: "Titan Claws", type: "Weapon", rarity: 24, power: 12, image: "images/titan_claws.jpg" },
  { name: "Mustard Blaster", type: "Weapon", rarity: 26, power: 15, image: "images/mustard.jpg" },
  { name: "BB Gun", type: "Weapon", rarity: 21, power: 15, image: "images/BB_gun.jpg" },
  { name: "Snowball Launcher", type: "Weapon", rarity: 21, power: 13, image: "images/snowball_launcher.jpg" },
  { name: "Pencil Crossbow", type: "Weapon", rarity: 25, power: 13, image: "images/pencil_crossbow.jpg" },
  { name: "Toaster Pistol", type: "Weapon", rarity: 26, power: 16, image: "images/toaster_pistol.jpg" },
  { name: "Ruler", type: "Weapon", rarity: 29, power: 12, image: "images/ruler.jpg" },
  { name: "Single Shooter", type: "Weapon", rarity: 3, power: 20, image: "images/single_shooter.jpg" },
  { name: "Burger", type: "Tool", rarity: 26, power: 12, image: "images/burger.jpg" },
  { name: "Skull Minigun", type: "Weapon", rarity: 30, power: 36, image: "images/skull_minigun.jpg" },
  { name: "Ogre Gun", type: "Weapon", rarity: 33, power: 14, image: "images/ogre_gun.jpg" },
  { name: "Energy Grenade", type: "Weapon", rarity: 30, power: 18, image: "images/energy_grenade.jpg" },
  { name: "Rocket Launcher", type: "Weapon", rarity: 7, power: 43, image: "images/rocket_launcher.jpg" },
  { name: "Ray Gun", type: "Weapon", rarity: 7, power: 43, image: "images/ray_gun.jpg" },
  { name: "Waffle Box", type: "Tool", rarity: 45, power: 25, image: "images/waffle_box.jpg" },
  { name: "Pumpkin Slinger", type: "Weapon", rarity: 29, power: 20, image: "images/pumpkin_slinger.jpg" },
  { name: "Wack Broom", type: "Weapon", rarity: 29, power: 12, image: "images/wack_broom.jpg" },
  { name: "Skull Crusher", type: "Weapon", rarity: 30, power: 12, image: "images/skull_crusher.jpg" },
  { name: "Knife", type: "Weapon", rarity: 30, power: 12, image: "images/knife.jpg" },
  { name: "Reaper Scythe", type: "Weapon", rarity: 32, power: 12, image: "images/reaper_scythe.jpg" },
  { name: "JackoBox T1", type: "Tool", rarity: 34, power: 10, image: "images/jackobox_T1.jpg" },
  { name: "Present Launcher", type: "Weapon", rarity: 35, power: 43, image: "images/present_launcher.jpg" },
  { name: "Candy Launcher", type: "Weapon", rarity: 35, power: 43, image: "images/candy_launcher.jpg" },
  { name: "Ketchup Blaster", type: "Weapon", rarity: 37, power: 15, image: "images/ketchup.jpg" },
  { name: "Squid Rifle", type: "Weapon", rarity: 37, power: 18, image: "images/squid_rifle.jpg" },
  { name: "Ticket Gun", type: "Weapon", rarity: 39, power: 20, image: "images/ticket_gun.jpg" },
  { name: "CandyCane Minigun", type: "Weapon", rarity: 40, power: 36, image: "images/candycane_minigun.jpg" },
  { name: "Nuke", type: "Tool", rarity: 9, power: 100, image: "images/nuke.jpg" },
  { name: "Pumpkin Launcher", type: "Weapon", rarity: 42, power: 50, image: "images/pumpkin_launcher.jpg" },
  { name: "Motorcycle", type: "Tool", rarity: 43, power: 30, image: "images/motorcycle.jpg" },
  { name: "Dark Sword", type: "Weapon", rarity: 43, power: 12, image: "images/dark_sword.jpg" },
  { name: "Enchanted Box", type: "Tool", rarity: 38, power: 20, image: "images/enchanted_box.jpg" },
  { name: "JackoBox T2", type: "Tool", rarity: 43, power: 10, image: "images/jackobox_T2.jpg" },
  { name: "Uncle Sam", type: "Weapon", rarity: 50, power: 36, image: "images/uncle_sam.jpg" },
  { name: "Firework Pistol", type: "Weapon", rarity: 52, power: 24, image: "images/firework_pistol.jpg" },
  { name: "Sparkler", type: "Weapon", rarity: 52, power: 12, image: "images/sparkler.jpg" },
  { name: "Flintlock Pistol", type: "Weapon", rarity: 52, power: 23, image: "images/flintlock_pistol.jpg" },
  { name: "USA Baton", type: "Weapon", rarity: 53, power: 12, image: "images/USA_baton.jpg" },
  { name: "Flag Wacker", type: "Weapon", rarity: 53, power: 12, image: "images/flag_wacker.jpg" },
  { name: "Bonk Franklin", type: "Weapon", rarity: 54, power: 12, image: "images/bonk_franklin.jpg" },
  { name: "JackoBox T3", type: "Tool", rarity: 56, power: 18, image: "images/jackobox_T3.jpg" },
  { name: "Ghost Gun", type: "Weapon", rarity: 55, power: 18, image: "images/ghost_gun.jpg" },
  { name: "JackoBox T4", type: "Tool", rarity: 58, power: 18, image: "images/jackobox_T4.jpg" },
  { name: "Squid RPG", type: "Weapon", rarity: 58, power: 43, image: "images/squid_launcher.jpg" },
  { name: "Vampire Crossbow", type: "Weapon", rarity: 58, power: 10, image: "images/vampire_crossbow.jpg" },
  { name: "Devil 50", type: "Weapon", rarity: 60, power: 22, image: "images/devil_50.jpg" },
  { name: "Zombie Sprayer", type: "Weapon", rarity: 60, power: 28, image: "images/zombie.jpg" },
  { name: "Halloween AK", type: "Weapon", rarity: 62, power: 21, image: "images/halloween_AK.jpg" },
  { name: "1Christmas2024", type: "Tool", rarity: 66, power: 15, image: "images/2024_1.jpg" },
  { name: "JackoBox T5", type: "Tool", rarity: 67, power: 23, image: "images/jackobox_T5.jpg" },
  { name: "Firework Tommy", type: "Weapon", rarity: 69, power: 20, image: "images/firework_tommy.jpg" },
  { name: "4Christmas2024", type: "Tool", rarity: 72, power: 15, image: "images/2024_4.jpg" },
  { name: "Bat Minigun", type: "Weapon", rarity: 73, power: 36, image: "images/bat_minigun.jpg" },
  { name: "USAK 47", type: "Weapon", rarity: 73, power: 30, image: "images/USAK.jpg" },
  { name: "Cherry Slinger", type: "Weapon", rarity: 73, power: 30, image: "images/cherry_slinger.jpg" },
  { name: "Ghost Launcher", type: "Weapon", rarity: 74, power: 41, image: "images/ghost_launcher.jpg" },
  { name: "Freedom Lazer", type: "Weapon", rarity: 74, power: 43, image: "images/lazer.jpg" },
  { name: "Musket", type: "Weapon", rarity: 82, power: 34, image: "images/musket.jpg" },
  { name: "3Christmas2024", type: "Tool", rarity: 77, power: 15, image: "images/2024_3.jpg" },
  { name: "Balloon", type: "Weapon", rarity: 76, power: 39, image: "images/balloon.jpg" },
  { name: "5Christmas2024", type: "Tool", rarity: 79, power: 15, image: "images/2024_5.jpg" },
  { name: "7Christmas2024", type: "Tool", rarity: 81, power: 15, image: "images/2024_7.jpg" },
  { name: "2Christmas2024", type: "Tool", rarity: 81, power: 15, image: "images/2024_2.jpg" },
  { name: "8Christmas2024", type: "Tool", rarity: 81, power: 15, image: "images/2024_8.jpg" },
  { name: "6Christmas2024", type: "Tool", rarity: 82, power: 15, image: "images/2024_6.jpg" },
  { name: "Cake Launcher", type: "Weapon", rarity: 85, power: 56, image: "images/cake_launcher.jpg" },
  { name: "Firework Bazooka", type: "Weapon", rarity: 85, power: 47, image: "images/firework_bazooka.jpg" },
  { name: "9Christmas2024", type: "Tool", rarity: 87, power: 15, image: "images/2024_9.jpg" },
  { name: "George Blastington", type: "Weapon", rarity: 95, power: 47, image: "images/george.jpg" },
  { name: "10Christmas2024", type: "Tool", rarity: 87, power: 15, image: "images/2024_10.png" },
  { name: "Spark Thrower", type: "Weapon", rarity: 100, power: 25, image: "images/spark_thrower.jpg" },
  { name: "Liberty Launcher", type: "Weapon", rarity: 100, power: 45, image: "images/LL.jpg" },
  { name: "Boombox", type: "Tool", rarity: 0, power: 5, image: "images/boombox.jpg" }
];

